# Run `conda env create -f environment.yml` to create the conda environment.
name: dropout-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - pip
  - pip:
      - -r requirements.txt
